### ISSUE TITLE
Error with dependencies

### ISSUE THREAD

**Issue by Snipeur060** [JD-P/simulacrabot#1]
Hi i try to use your code but we have many problem first 
all of the depedencies is not sattisfied (einops, ldm, dlib)
but ldm we have a problem with this module
first this module use print without ()
(SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.face_rec_model_path)?)
After replace all
An new error come 
and this error lock all and block the execution 
error with lmd 
Traceback (most recent call last):
  File "simulacra.py", line 15, in <module>
    from simulacra_glide_sample import main as gen
  File "/home/container/simulacrabot/simulacra_glide_sample.py", line 14, in <module>
    from ldm.util import instantiate_from_config
ModuleNotFoundError: No module named 'ldm.util'; 'ldm' is not a package

So the error turn around the lmd module
if you try to juste import lmd you have this 
ERROR: Could not find a version that satisfies the requirement lmd (from versions: none)
ERROR: No matching distribution found for lmd

**Comment by JD-P** [comment]
Hi there, this is because I missed a step in my README at the final part where you symlink the latent-diffusion repo's library directories:

`ln -s stable-diffusion/ldm ./ldm`

I hope this helps you.

**Comment by Snipeur060** [comment]
I will try thanks :-)
